filter ospf4_import {
        if (net ~ OSPF_NET4) then accept;
        reject;
}

filter ospf6_import {
        if (net ~ OSPF_NET6) then accept;
        reject;
}

protocol ospf v2 ospf4 {
        ipv4 {
                import filter ospf4_import;
                export none;
        };

        area 0 {
                interface "dummy1" {
                        stub;
                };
                stubnet LOOP_IP4;
                stubnet NEO_LOOP_IP4;
                interface "loop*" { type ptp; cost 200; hello 5; dead 20; };
        };
}

protocol ospf v3 ospf6 {
        ipv6 {
                import filter ospf6_import;
                export none;
        };

        area 0 {
                interface "dummy1" {
                        stub;
                };
                stubnet LOOP_IP6;
                stubnet NEO_LOOP_IP6;
		        interface "loop*" { type ptp; cost 30; hello 5; dead 20; };
	};
}

