protocol bgp FLAPALERTED {
    local 172.20.5.66 as 4242420088;
    neighbor 172.20.5.66 as 4242420088 port 1790;

    ipv4 {
        extended next hop on;
        add paths on;
        export all;
        import none;
    };

    ipv6 {
        add paths on;
        export all;
        import none;
    };
}
