# this is a example

protocol bfd {
        interface "ztrnctts5x" {
                min rx interval 1000 ms;
                min tx interval 1000 ms;
                multiplier 3;
        };
	
	interface "zt3vg3w4vs" {
		min rx interval 1000 ms;
		min tx interval 1000 ms;
		multiplier 3;
	};
}

protocol bgp nedifinita_ix from dnix {
    neighbor fd10:127:42:ffff::1 as 4204549999;
}

protocol bgp beacon_ix from dnix {
    neighbor fd8d:0a91:5047:2a22:f599:930e:5be1:1576%zt3vg3w4vs as 4211179999;
}
