protocol bgp ROUTE_COLLECTOR
{
  local as 4242420088;
  neighbor fd42:d42:d42:179::1 as 4242422602;
  # enable multihop as the collector is not locally connected
  multihop;

  ipv4 {
    # export all available paths to the collector    
    add paths tx;

    # import/export filters
    import none;
    export filter dn42_collector_export;
  };

  ipv6 {
    # export all available paths to the collector    
    add paths tx;

    # import/export filters
    import none;
    export filter dn42_collector_export;
  };
}

